whisper: # wyoming endpoint for HASS
    container_name: whisper
    command:
      --uri tcp://0.0.0.0:10300
      --api http://whispercpp:8910/inference
      --debug
    image: # use this here as-is: https://github.com/ser/wyoming-whisper-api-client/blob/main/Dockerfile
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=Europe/Vienna
    restart: unless-stopped
    ports:
      - 10301:10300
    networks:
      - whisper

whispercpp: # whisper-server backend for wyoming 
    container_name: whispercpp
    command: 
      --language de
      --ov-e-device GPU
      --beam-size 5
      --model /data/ggml-medium.bin
      --host 0.0.0.0
      --port 8910
      --debug-mode
    image: #from whispercpp-openvino.Dockerfile
    devices:
      - /dev/dri:/dev/dri
    security_opt:
      - seccomp=unconfined
    group_add:
      - 44 # use the id returned by  $(getent group video)
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - #storage:/data
    environment:
      - TZ=Europe/Vienna
    restart: unless-stopped
    expose:
      - 8910
    networks:
      - whisper
