name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build the Docker image
      run: |
        IMAGE_ID=ghcr.io/${{ github.repository_owner }}/my-image-name
        VERSION=$(date +%s)
        docker build . --file wyoming-whisper-api-client-Dockerfile --tag $IMAGE_ID:$VERSION
        docker tag $IMAGE_ID:$VERSION $IMAGE_ID:latest

    - name: Push the Docker image
      run: |
        IMAGE_ID=ghcr.io/${{ github.repository_owner }}/my-image-name
        VERSION=$(date +%s)
        docker push $IMAGE_ID:$VERSION
        docker push $IMAGE_ID:latest
